# Generated by Django 5.2.14 on 2026-05-09 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('registro', 'Registro de novo usuario'), ('ativacao', 'Ativacao de conta'), ('disciplina_criada', 'Disciplina criada'), ('permissao_disciplina_alterada', 'Permissao em disciplina alterada'), ('post_criado', 'Post criado'), ('post_editado', 'Post editado'), ('post_removido', 'Post removido'), ('marcou_melhor', 'Marcou resposta como melhor'), ('desmarcou_melhor', 'Desmarcou melhor resposta'), ('denunciou', 'Denunciou conteudo'), ('denuncia_resolvida', 'Denuncia resolvida')], db_index=True, max_length=50)),
                ('objeto_id', models.UUIDField(blank=True, null=True)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('descricao', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que executou a acao (nulo se anonimo ou usuario removido)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_auditadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', '-created_at'], name='audit_log_usuario_44cdc9_idx'), models.Index(fields=['acao', '-created_at'], name='audit_log_acao_f08acc_idx'), models.Index(fields=['content_type', 'objeto_id'], name='audit_log_content_2e3561_idx')],
            },
        ),
    ]
