# Generated by Django 5.2.14 on 2026-05-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='acao',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('registro', 'Registro de novo usuario'), ('ativacao', 'Ativacao de conta'), ('disciplina_criada', 'Disciplina criada'), ('permissao_disciplina_alterada', 'Permissao em disciplina alterada'), ('post_criado', 'Post criado'), ('post_editado', 'Post editado'), ('post_removido', 'Post removido'), ('marcou_melhor', 'Marcou resposta como melhor'), ('desmarcou_melhor', 'Desmarcou melhor resposta'), ('denunciou', 'Denunciou conteudo'), ('oportunidade_criada', 'Oportunidade de voluntariado criada'), ('inscricao_voluntariado', 'Inscricao em oportunidade de voluntariado'), ('inscricao_aprovada', 'Inscricao em voluntariado aprovada'), ('inscricao_rejeitada', 'Inscricao em voluntariado rejeitada'), ('inscricao_removida', 'Participante removido de oportunidade'), ('voluntariado_concluido', 'Voluntariado concluido e certificado emitido'), ('denuncia_resolvida', 'Denuncia resolvida')], db_index=True, max_length=50),
        ),
    ]
