# Generated by Django 5.2.14 on 2026-08-13 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0007_disciplina_ementa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoTrabalho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
                ('especificacao_propria', models.TextField(blank=True, default='', help_text='Tema especifico deste grupo. Vazio significa usar o do trabalho.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo de Trabalho',
                'verbose_name_plural': 'Grupos de Trabalho',
                'db_table': 'grupo_trabalho',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('disciplina', 'Turma da disciplina'), ('grupo', 'Grupo de trabalho'), ('privada', 'Conversa privada')], db_index=True, max_length=12)),
                ('titulo', models.CharField(blank=True, default='', max_length=160)),
                ('semestre', models.CharField(blank=True, default='', max_length=10)),
                ('arquivada_em', models.DateTimeField(blank=True, help_text='Preenchido no encerramento do semestre; torna a conversa somente leitura', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(blank=True, help_text='Preenchido nas conversas de turma e de grupo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='forum.disciplina')),
                ('grupo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversa', to='colaboracao.grupotrabalho')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'db_table': 'conversa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembroGrupo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('e_lider', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='colaboracao.grupotrabalho')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_trabalho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro de Grupo',
                'verbose_name_plural': 'Membros de Grupo',
                'db_table': 'membro_grupo',
            },
        ),
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo', models.TextField(blank=True, default='')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='conversas/%Y/%m/')),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('tipo_midia', models.CharField(choices=[('texto', 'Somente texto'), ('imagem', 'Imagem'), ('documento', 'Documento'), ('audio', 'Audio')], default='texto', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='colaboracao.conversa')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'db_table': 'mensagem_chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteConversa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lido_ate', models.DateTimeField(blank=True, help_text='Momento da ultima mensagem lida por esta pessoa', null=True)),
                ('silenciada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='colaboracao.conversa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante de Conversa',
                'verbose_name_plural': 'Participantes de Conversa',
                'db_table': 'participante_conversa',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAjuda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, default='', help_text='Complemento escrito por quem pediu ajuda')),
                ('destino', models.CharField(choices=[('monitoria', 'Monitoria'), ('professor', 'Professor'), ('ambos', 'Monitoria e professor')], default='ambos', max_length=12)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_atendimento', 'Em atendimento'), ('resolvida', 'Resolvida')], db_index=True, default='aberta', max_length=15)),
                ('resposta', models.TextField(blank=True, default='')),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajudas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='colaboracao.mensagemchat')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajudas_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitacao de Ajuda',
                'verbose_name_plural': 'Solicitacoes de Ajuda',
                'db_table': 'solicitacao_ajuda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('especificacao', models.TextField(blank=True, default='', help_text='Enunciado valido para todos os grupos')),
                ('total_grupos', models.PositiveSmallIntegerField(help_text='Quantidade de grupos previstos na turma')),
                ('tamanho_maximo', models.PositiveSmallIntegerField(default=5, help_text='Maximo de participantes por grupo')),
                ('modo_formacao', models.CharField(choices=[('professor', 'O professor monta os grupos'), ('alunos', 'Os alunos se organizam'), ('sorteio', 'Sorteio automatico entre os matriculados')], default='alunos', max_length=15)),
                ('prazo_entrega', models.DateField()),
                ('encerrado', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabalhos_criados', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabalhos', to='forum.disciplina')),
            ],
            options={
                'verbose_name': 'Trabalho em Grupo',
                'verbose_name_plural': 'Trabalhos em Grupo',
                'db_table': 'trabalho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='grupotrabalho',
            name='trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='colaboracao.trabalho'),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['tipo', 'disciplina'], name='conversa_tipo_b6d081_idx'),
        ),
        migrations.AddConstraint(
            model_name='membrogrupo',
            constraint=models.UniqueConstraint(fields=('grupo', 'usuario'), name='unique_membro_por_grupo'),
        ),
        migrations.AddIndex(
            model_name='mensagemchat',
            index=models.Index(fields=['conversa', '-created_at'], name='mensagem_ch_convers_5ae281_idx'),
        ),
        migrations.AddConstraint(
            model_name='participanteconversa',
            constraint=models.UniqueConstraint(fields=('conversa', 'usuario'), name='unique_participante_por_conversa'),
        ),
        migrations.AddIndex(
            model_name='solicitacaoajuda',
            index=models.Index(fields=['status', '-created_at'], name='solicitacao_status_313dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='trabalho',
            index=models.Index(fields=['disciplina', 'encerrado'], name='trabalho_discipl_3540b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='grupotrabalho',
            constraint=models.UniqueConstraint(fields=('trabalho', 'nome'), name='unique_grupo_nome_por_trabalho'),
        ),
    ]
