# Generated by Django 5.2.14 on 2026-09-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboracao', '0002_arquivotrabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='tipo',
            field=models.CharField(choices=[('disciplina', 'Turma da disciplina'), ('grupo', 'Grupo de trabalho'), ('monitoria', 'Monitoria da disciplina'), ('privada', 'Conversa privada')], db_index=True, max_length=12),
        ),
    ]
