# Generated by Django 5.2.14 on 2026-05-08 22:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=100)),
                ('semestre', models.CharField(help_text='Ex: 2026.1', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'db_table': 'disciplina',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, help_text='Vazio em respostas', max_length=255)),
                ('conteudo', models.TextField()),
                ('e_melhor', models.BooleanField(default=False)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('pontuacao', models.IntegerField(default=0, help_text='Cache de votos')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='forum.disciplina')),
                ('post_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='forum.post')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEdicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo_anterior', models.TextField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edicoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_edicoes', to='forum.post')),
            ],
            options={
                'verbose_name': 'Historico de Edicao',
                'verbose_name_plural': 'Historicos de Edicao',
                'db_table': 'historico_edicao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='posts/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho_bytes', models.BigIntegerField()),
                ('tipo_mime', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='forum.post')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'db_table': 'arquivo',
            },
        ),
        migrations.CreateModel(
            name='AlertaConteudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Analise'), ('procedente', 'Procedente'), ('improcedente', 'Improcedente')], default='pendente', max_length=20)),
                ('resolucao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('denunciante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_feitas', to=settings.AUTH_USER_MODEL)),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_resolvidas', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='forum.post')),
            ],
            options={
                'verbose_name': 'Alerta de Conteudo',
                'verbose_name_plural': 'Alertas de Conteudo',
                'db_table': 'alerta_conteudo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='forum.post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'db_table': 'voto',
            },
        ),
        migrations.CreateModel(
            name='PermissaoDisciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('papel', models.CharField(choices=[('aluno', 'Aluno'), ('monitor', 'Monitor'), ('professor', 'Professor')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='forum.disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_disciplina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissao de Disciplina',
                'verbose_name_plural': 'Permissoes de Disciplinas',
                'db_table': 'permissao_disciplina',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'disciplina'), name='unique_usuario_disciplina')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['disciplina', 'post_pai'], name='post_discipl_4cb8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['autor'], name='post_autor_i_c48a45_idx'),
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(fields=('usuario', 'post'), name='unique_voto_usuario_post'),
        ),
    ]
