# Generated by Django 5.2.14 on 2026-05-09 03:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='post',
            name='total_reacoes_persiste',
            field=models.IntegerField(default=0, help_text='Cache de quantos usuarios marcaram que a duvida persiste'),
        ),
        migrations.CreateModel(
            name='ReacaoPersiste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True, help_text='Opcional: explicacao do que ainda nao ficou claro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(help_text='Deve ser uma resposta (post com post_pai)', on_delete=django.db.models.deletion.CASCADE, related_name='reacoes_persiste', to='forum.post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes_persiste', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reacao Duvida Persiste',
                'verbose_name_plural': 'Reacoes Duvida Persiste',
                'db_table': 'reacao_persiste',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'post'), name='unique_reacao_persiste_usuario_post')],
            },
        ),
    ]
