# Generated by Django 5.2.14 on 2026-08-12 03:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alertaconteudo_assumido_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('grau', models.CharField(default='bacharelado', help_text='Bacharelado, licenciatura, tecnologico', max_length=30)),
                ('versao_ppc', models.CharField(blank=True, help_text='Versao do PPC que originou a matriz, ex: Jan/2025', max_length=30)),
                ('periodos', models.PositiveSmallIntegerField(default=8, help_text='Quantidade de periodos previstos na matriz')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['periodo_sugerido', 'codigo'], 'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AddField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Carga horaria total em horas', null=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='optativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='periodo_sugerido',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Periodo previsto na matriz curricular', null=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='pre_requisitos',
            field=models.ManyToManyField(blank=True, help_text='Disciplinas que precisam ser cursadas antes', related_name='libera', to='forum.disciplina'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.CharField(help_text='Semestre de oferta, ex: 2026.1', max_length=10),
        ),
        # O campo 'curso' era texto livre e passou a ser chave estrangeira.
        # O Postgres nao converte texto em UUID, entao a coluna antiga e
        # descartada e a nova criada em seguida. O nome do curso gravado como
        # texto se perde, o que e aceitavel porque a importacao da matriz do
        # PPC recadastra as disciplinas com o vinculo correto.
        migrations.RemoveField(
            model_name='disciplina',
            name='curso',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(blank=True, help_text='Nulo em disciplinas de outros institutos ainda nao cadastradas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='forum.curso'),
        ),
        migrations.AddIndex(
            model_name='disciplina',
            index=models.Index(fields=['curso', 'periodo_sugerido'], name='disciplina_curso_i_72134c_idx'),
        ),
    ]
