# Generated by Django 5.2.14 on 2026-08-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_curso_alter_disciplina_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='co_requisitos',
            field=models.ManyToManyField(blank=True, help_text='Disciplinas cursadas no mesmo periodo, como TCC1 e Metodologia Cientifica', to='forum.disciplina'),
        ),
    ]
