# Generated by Django 5.2.14 on 2026-08-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_post_motivo_restricao_post_restrito_post_restrito_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='ementa',
            field=models.TextField(blank=True, default='', help_text='Descricao da disciplina, conforme o PPC'),
        ),
    ]
