# Generated by Django 5.2.14 on 2026-05-14 23:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0002_remove_voto_tipo_post_total_reacoes_persiste_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSemestral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semestre', models.CharField(db_index=True, help_text='Ex: 2026.1', max_length=10)),
                ('posicao', models.PositiveIntegerField()),
                ('pontos', models.IntegerField()),
                ('nome_usuario', models.CharField(max_length=255)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings_semestrais', to='forum.disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_ranking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ranking Semestral',
                'verbose_name_plural': 'Rankings Semestrais',
                'db_table': 'ranking_semestral',
                'ordering': ['disciplina', 'semestre', 'posicao'],
                'indexes': [models.Index(fields=['disciplina', 'semestre', 'posicao'], name='ranking_sem_discipl_e4d1a3_idx')],
                'constraints': [models.UniqueConstraint(fields=('disciplina', 'semestre', 'usuario'), name='unique_ranking_disciplina_semestre_usuario')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioDisciplinaReputacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pontos', models.IntegerField(db_index=True, default=0)),
                ('total_posts', models.PositiveIntegerField(default=0)),
                ('total_respostas', models.PositiveIntegerField(default=0)),
                ('total_votos_recebidos', models.PositiveIntegerField(default=0)),
                ('total_melhores_respostas', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputacoes', to='forum.disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputacoes_disciplina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reputacao por Disciplina',
                'verbose_name_plural': 'Reputacoes por Disciplina',
                'db_table': 'usuario_disciplina_reputacao',
                'ordering': ['-pontos'],
                'indexes': [models.Index(fields=['disciplina', '-pontos'], name='usuario_dis_discipl_f76c7e_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'disciplina'), name='unique_reputacao_usuario_disciplina')],
            },
        ),
    ]
