"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from decouple import config, Csv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())


# Application definition

INSTALLED_APPS = [
    # O daphne precisa vir antes do staticfiles para assumir o runserver
    # e atender WebSocket em desenvolvimento.
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'autenticacao',
    'forum',
    'notificacoes',
    'auditoria',
    'voluntariado',
    'colaboracao',
    'busca',
]

# Busca semantica do forum.
#
# Desligada por padrao porque depende de um modelo de aprendizado de maquina
# que nem todo ambiente precisa carregar: sem ela, a busca do forum responde
# por correspondencia de termos e o resto da plataforma nao muda. Ligar exige,
# alem da variavel, `pip install sentence-transformers pgvector` e a extensao
# vector criada no PostgreSQL.
BUSCA_SEMANTICA_ATIVA = config('BUSCA_SEMANTICA_ATIVA', default=False, cast=bool)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Precisa vir logo apos o SecurityMiddleware: e ele que entrega os
    # arquivos estaticos em producao, no lugar de um servidor web separado.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditoria.middleware.AuditoriaContextoMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # O index.html gerado pelo build do React e tratado como template, o
        # que permite ao Django devolve-lo em qualquer rota da interface.
        'DIRS': [BASE_DIR / 'frontend' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# ===== Log das conexoes WebSocket =====
# Mostra no terminal por que uma conexao foi aceita ou recusada, o que evita
# depurar handshake no escuro quando o frontend so reporta erro de conexao.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'config.ws_auth': {'handlers': ['console'], 'level': 'INFO'},
        'notificacoes': {'handlers': ['console'], 'level': 'INFO'},
    },
}


# ===== Redis e camada de canais (Django Channels) =====
# O Redis intermedia as mensagens entre os processos do servidor, de modo que
# uma notificacao criada em uma requisicao HTTP alcance o WebSocket do usuario
# mesmo que ele esteja conectado em outro worker.
#
# Usamos o backend de publicacao e assinatura (pub/sub) em vez do backend de
# filas. Nosso uso e difusao para um grupo, sem necessidade de guardar a
# mensagem: quem nao estava conectado no momento vai ver a notificacao pela
# API, que le do PostgreSQL. O backend de filas manteria uma leitura
# bloqueante no Redis, que estoura o tempo limite em conexoes ociosas.

# ===== Camada de canais e cache =====
#
# O Redis existe aqui para duas coisas: distribuir mensagens de WebSocket
# entre varias instancias da aplicacao e guardar dados de vida curta, como os
# refresh tokens invalidados.
#
# Quando a aplicacao roda em uma instancia unica, nenhuma das duas exige um
# servidor externo: a camada em memoria do Channels distribui as mensagens
# dentro do proprio processo, e o cache local guarda os tokens. Foi o caso da
# implantacao gratuita, e evitar o Redis ali removeu um servico a configurar,
# monitorar e ver cair.
#
# Em qualquer ambiente com mais de uma instancia o Redis volta a ser
# obrigatorio, porque uma mensagem publicada em um processo precisa alcancar
# quem esta conectado no outro. Por isso o padrao continua sendo ele.
USAR_REDIS = config('USAR_REDIS', default=True, cast=bool)

REDIS_HOST = config('REDIS_HOST', default='127.0.0.1')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
REDIS_DB_CHANNELS = config('REDIS_DB_CHANNELS', default=1, cast=int)

REDIS_URL_CHANNELS = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CHANNELS}'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.pubsub.RedisPubSubChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL_CHANNELS],
        },
    },
}


# ===== Cache =====
# Banco separado do usado pelos canais, para que um flush em um nao derrube o
# outro. E aqui que fica a lista de refresh tokens invalidados: sao registros
# de vida curta, consultados a cada renovacao e descartados na expiracao, o que
# o TTL do Redis resolve sozinho, sem tabela crescendo no PostgreSQL.

REDIS_DB_CACHE = config('REDIS_DB_CACHE', default=2, cast=int)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CACHE}',
    },
}

if not USAR_REDIS:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'},
    }
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'plataforma-unifei',
        },
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# DATABASE_URL tem prioridade sobre as variaveis separadas. Os servicos de
# banco gerenciados entregam a conexao nesse formato unico, e montar a URL a
# partir de cinco variaveis soltas so cria oportunidade de errar uma delas.

DATABASE_URL = config('DATABASE_URL', default='')

if DATABASE_URL:
    from urllib.parse import unquote, urlparse

    url = urlparse(DATABASE_URL)

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': url.path.lstrip('/'),
            'USER': unquote(url.username or ''),
            'PASSWORD': unquote(url.password or ''),
            'HOST': url.hostname or '',
            'PORT': str(url.port or 5432),
            # Conexao persistente: em plano gratuito, abrir uma conexao nova a
            # cada requisicao pesa mais do que mante-la aberta.
            'CONN_MAX_AGE': 600,
            'OPTIONS': {'sslmode': config('DB_SSLMODE', default='require')},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# O build do React entra como arquivo estatico do Django, servido pela mesma
# aplicacao que responde a API. Manter os dois no mesmo endereco evita CORS e
# faz o WebSocket apontar para a propria origem, sem configuracao extra.
STATICFILES_DIRS = (
    [BASE_DIR / 'frontend' / 'dist'] if (BASE_DIR / 'frontend' / 'dist').exists() else []
)

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ===== Armazenamento =====
#
# Em producao, o disco da instancia e efemero: some a cada reinicio. Foto de
# perfil, capa de oportunidade e o PDF do certificado precisam, portanto, de
# armazenamento externo. Usamos um servico compativel com S3, configurado por
# variavel de ambiente; sem essas variaveis, o projeto continua gravando em
# disco, que e o comportamento correto em desenvolvimento.
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='')

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        # WhiteNoise comprime e versiona os arquivos estaticos, dispensando um
        # servidor web separado so para entrega-los.
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

if AWS_STORAGE_BUCKET_NAME:
    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL')
    AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default='')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='auto')
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False

    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
    }


# ===== Seguranca em producao =====
# Estes ajustes dependem de HTTPS e por isso ficam condicionados ao DEBUG.
# Ativa-los em desenvolvimento redirecionaria o localhost para https e
# impediria o navegador de enviar os cookies, derrubando o ambiente local.

if not DEBUG:
    # Redireciona qualquer acesso http para https.
    SECURE_SSL_REDIRECT = True

    # Cookies de sessao e de CSRF trafegam apenas por conexao cifrada, o que
    # impede que sejam capturados por quem estiver observando a rede.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = False  # o frontend precisa ler o token para envia-lo

    # HSTS instrui o navegador a nunca mais acessar o dominio por http.
    # O valor comeca baixo de proposito: o navegador guarda essa instrucao
    # pelo tempo indicado, e um prazo longo com o certificado mal configurado
    # deixaria o site inacessivel ate o prazo vencer. Aumentar para 31536000
    # (um ano) depois de confirmar que o https esta estavel.
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=3600, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    # Preload permanece desligado por decisao de projeto. Entrar na lista de
    # pre-carregamento dos navegadores exige max-age de no minimo um ano e a
    # saida leva meses para propagar, ja que a instrucao vai embutida na
    # proxima versao de cada navegador. Nao e uma escolha compativel com um
    # dominio institucional que ainda passara por validacao com usuarios.
    SECURE_HSTS_PRELOAD = False

    # Atras de nginx ou load balancer, o Django recebe a requisicao por http
    # e precisa deste cabecalho para saber que a conexao original era https.
    # Sem isso, o SECURE_SSL_REDIRECT entraria em laco infinito.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Impede que o navegador tente adivinhar o tipo do arquivo, o que evita
    # que um upload seja interpretado como script.
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Bloqueia a exibicao do site dentro de iframe de terceiros (clickjacking).
    X_FRAME_OPTIONS = 'DENY'

    SECURE_REFERRER_POLICY = 'same-origin'

    # W021 alerta que o preload esta desligado. E intencional, pelo motivo
    # descrito acima, entao silenciamos para que o check --deploy volte a
    # sinalizar apenas problemas reais.
    SILENCED_SYSTEM_CHECKS = ['security.W021']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'autenticacao.Usuario'

# ===== Django REST Framework =====
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.PaginacaoPadrao',
    'PAGE_SIZE': 20,
}

# ===== Simple JWT =====
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    # A invalidacao nao usa a tabela do SimpleJWT: e feita no Redis, pela
    # lista implementada em autenticacao/tokens.py.
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# ===== Media files (uploads) =====
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Limite de tamanho de upload (alinhado com validators do forum)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

# ===== Email =====
# Em desenvolvimento, os emails sao impressos no terminal em vez de enviados.
# Em producao, trocar EMAIL_BACKEND para SMTP real (Gmail, SendGrid, etc).
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='nao-responda@plataforma-unifei.local')

# ===== Codigo de ativacao =====
CODIGO_ATIVACAO_VALIDADE_MINUTOS = 30
CODIGO_ATIVACAO_MAX_TENTATIVAS = 5

# ===== drf-spectacular (documentacao OpenAPI) =====
SPECTACULAR_SETTINGS = {
    'TITLE': 'Plataforma UNIFEI - API',
    'DESCRIPTION': (
        'API REST da plataforma que integra forum academico organizado por '
        'disciplina com sistema de voluntariado universitario. '
        'Trabalho de Conclusao de Curso - Ciencia da Computacao - UNIFEI.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Autenticacao', 'description': 'Login, registro e ativacao de conta'},
        {'name': 'Forum', 'description': 'Disciplinas, posts, votos, denuncias e arquivos'},
        {'name': 'Notificacoes', 'description': 'Notificacoes do usuario'},
        {'name': 'Auditoria', 'description': 'Registros de auditoria do sistema'},
        {'name': 'Voluntariado', 'description': 'Oportunidades, inscricoes e certificados'},
        {'name': 'Reputacao', 'description': 'Reputacao por disciplina e rankings'},
    ],
}