"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from decouple import config, Csv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())


# Application definition

INSTALLED_APPS = [
    # O daphne precisa vir antes do staticfiles para assumir o runserver
    # e atender WebSocket em desenvolvimento.
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'autenticacao',
    'forum',
    'notificacoes',
    'auditoria',
    'voluntariado',
    'reputacao',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditoria.middleware.AuditoriaContextoMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# ===== Log das conexoes WebSocket =====
# Mostra no terminal por que uma conexao foi aceita ou recusada, o que evita
# depurar handshake no escuro quando o frontend so reporta erro de conexao.

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'config.ws_auth': {'handlers': ['console'], 'level': 'INFO'},
        'notificacoes': {'handlers': ['console'], 'level': 'INFO'},
    },
}


# ===== Redis e camada de canais (Django Channels) =====
# O Redis intermedia as mensagens entre os processos do servidor, de modo que
# uma notificacao criada em uma requisicao HTTP alcance o WebSocket do usuario
# mesmo que ele esteja conectado em outro worker.
#
# Usamos o backend de publicacao e assinatura (pub/sub) em vez do backend de
# filas. Nosso uso e difusao para um grupo, sem necessidade de guardar a
# mensagem: quem nao estava conectado no momento vai ver a notificacao pela
# API, que le do PostgreSQL. O backend de filas manteria uma leitura
# bloqueante no Redis, que estoura o tempo limite em conexoes ociosas.

REDIS_HOST = config('REDIS_HOST', default='127.0.0.1')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
REDIS_DB_CHANNELS = config('REDIS_DB_CHANNELS', default=1, cast=int)

REDIS_URL_CHANNELS = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CHANNELS}'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.pubsub.RedisPubSubChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL_CHANNELS],
        },
    },
}


# ===== Cache =====
# Banco separado do usado pelos canais, para que um flush em um nao derrube o
# outro. E aqui que fica a lista de refresh tokens invalidados: sao registros
# de vida curta, consultados a cada renovacao e descartados na expiracao, o que
# o TTL do Redis resolve sozinho, sem tabela crescendo no PostgreSQL.

REDIS_DB_CACHE = config('REDIS_DB_CACHE', default=2, cast=int)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CACHE}',
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'autenticacao.Usuario'

# ===== Django REST Framework =====
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.PaginacaoPadrao',
    'PAGE_SIZE': 20,
}

# ===== Simple JWT =====
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    # A invalidacao nao usa a tabela do SimpleJWT: e feita no Redis, pela
    # lista implementada em autenticacao/tokens.py.
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# ===== Media files (uploads) =====
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Limite de tamanho de upload (alinhado com validators do forum)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

# ===== Email =====
# Em desenvolvimento, os emails sao impressos no terminal em vez de enviados.
# Em producao, trocar EMAIL_BACKEND para SMTP real (Gmail, SendGrid, etc).
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='nao-responda@plataforma-unifei.local')

# ===== Codigo de ativacao =====
CODIGO_ATIVACAO_VALIDADE_MINUTOS = 30
CODIGO_ATIVACAO_MAX_TENTATIVAS = 5

# ===== drf-spectacular (documentacao OpenAPI) =====
SPECTACULAR_SETTINGS = {
    'TITLE': 'Plataforma UNIFEI - API',
    'DESCRIPTION': (
        'API REST da plataforma que integra forum academico organizado por '
        'disciplina com sistema de voluntariado universitario. '
        'Trabalho de Conclusao de Curso - Ciencia da Computacao - UNIFEI.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': [
        {'name': 'Autenticacao', 'description': 'Login, registro e ativacao de conta'},
        {'name': 'Forum', 'description': 'Disciplinas, posts, votos, denuncias e arquivos'},
        {'name': 'Notificacoes', 'description': 'Notificacoes do usuario'},
        {'name': 'Auditoria', 'description': 'Registros de auditoria do sistema'},
        {'name': 'Voluntariado', 'description': 'Oportunidades, inscricoes e certificados'},
        {'name': 'Reputacao', 'description': 'Reputacao por disciplina e rankings'},
    ],
}