# Generated by Django 5.2.14 on 2026-05-13 15:01

import django.db.models.deletion
import uuid
import voluntariado.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoVoluntariado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('removida', 'Removida'), ('desistente', 'Desistente'), ('concluida', 'Concluida')], db_index=True, default='pendente', max_length=20)),
                ('motivacao', models.TextField(blank=True, help_text='Texto livre escrito pelo estudante no momento da inscricao')),
                ('avaliado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_decisao', models.TextField(blank=True, help_text='Justificativa para aprovacao, rejeicao ou remocao')),
                ('horas_realizadas', models.PositiveIntegerField(blank=True, help_text='Horas efetivamente cumpridas, registradas na conclusao', null=True)),
                ('avaliacao_organizacao', models.TextField(blank=True, help_text='Comentario da ONG sobre o desempenho do voluntario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avaliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_avaliadas', to=settings.AUTH_USER_MODEL)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_voluntariado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscricao em Voluntariado',
                'verbose_name_plural': 'Inscricoes em Voluntariado',
                'db_table': 'inscricao_voluntariado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_estudante', models.CharField(max_length=255)),
                ('cpf_estudante', models.CharField(max_length=11)),
                ('nome_oportunidade', models.CharField(max_length=255)),
                ('nome_organizacao', models.CharField(max_length=255)),
                ('area_atuacao', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('horas_realizadas', models.PositiveIntegerField()),
                ('codigo_validacao', models.CharField(db_index=True, default=voluntariado.models.gerar_codigo_certificado, editable=False, max_length=20, unique=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='certificados/%Y/%m/')),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificado', to='voluntariado.inscricaovoluntariado')),
            ],
            options={
                'verbose_name': 'Certificado de Voluntariado',
                'verbose_name_plural': 'Certificados de Voluntariado',
                'db_table': 'certificado',
                'ordering': ['-emitido_em'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('area', models.CharField(choices=[('educacao', 'Educacao'), ('saude', 'Saude'), ('meio_ambiente', 'Meio Ambiente'), ('assistencia_social', 'Assistencia Social'), ('direitos_humanos', 'Direitos Humanos'), ('cultura', 'Cultura e Arte'), ('tecnologia', 'Tecnologia'), ('esporte', 'Esporte'), ('outro', 'Outro')], db_index=True, max_length=30)),
                ('local', models.CharField(help_text='Cidade/local de realizacao', max_length=255)),
                ('vagas', models.PositiveIntegerField(default=1)),
                ('carga_horaria_total', models.PositiveIntegerField(help_text='Carga horaria estimada em horas')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('prazo_inscricao', models.DateField()),
                ('requer_aprovacao', models.BooleanField(default=True, help_text='Se False, inscricoes sao aprovadas automaticamente')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], db_index=True, default='ativa', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizacao', models.ForeignKey(help_text='Usuario com RoleGlobal=ong ou admin que publicou a oportunidade', on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades_publicadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oportunidade de Voluntariado',
                'verbose_name_plural': 'Oportunidades de Voluntariado',
                'db_table': 'oportunidade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inscricaovoluntariado',
            name='oportunidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='voluntariado.oportunidade'),
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['area', 'status'], name='oportunidad_area_14a811_idx'),
        ),
        migrations.AddIndex(
            model_name='oportunidade',
            index=models.Index(fields=['data_inicio'], name='oportunidad_data_in_e72a03_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscricaovoluntariado',
            constraint=models.UniqueConstraint(fields=('oportunidade', 'estudante'), name='unique_inscricao_estudante_oportunidade'),
        ),
    ]
