# Generated by Django 5.2.14 on 2026-08-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de capa exibida no cartao da oportunidade', null=True, upload_to='oportunidades/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='o_que_fazer',
            field=models.TextField(blank=True, default='', help_text='Atividades que o voluntario ira desempenhar'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='requisitos',
            field=models.TextField(blank=True, default='', help_text='O que se espera de quem se inscrever'),
        ),
    ]
