# Generated by Django 5.2.14 on 2026-08-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntariado', '0002_oportunidade_imagem_oportunidade_o_que_fazer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='contribuicao',
            field=models.CharField(blank=True, default='', help_text='O que foi entregue, ja formatado: "40 pecas de agasalho". Vazio nas acoes presenciais, onde a contribuicao e o tempo', max_length=120),
        ),
        migrations.AddField(
            model_name='certificado',
            name='modalidade',
            field=models.CharField(default='presencial', help_text='Modalidade da acao no momento da emissao', max_length=12),
        ),
        migrations.AddField(
            model_name='inscricaovoluntariado',
            name='item_doado',
            field=models.CharField(blank=True, default='', help_text='Descricao do que foi entregue, quando a campanha aceita itens variados', max_length=160),
        ),
        migrations.AddField(
            model_name='inscricaovoluntariado',
            name='quantidade_confirmada',
            field=models.PositiveIntegerField(blank=True, help_text='O que a organizacao confirmou ter recebido. E o unico valor que entra na contagem da campanha', null=True),
        ),
        migrations.AddField(
            model_name='inscricaovoluntariado',
            name='quantidade_declarada',
            field=models.PositiveIntegerField(blank=True, help_text='O que o estudante informou que iria entregar', null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='horas_por_participacao',
            field=models.PositiveSmallIntegerField(default=0, help_text='Horas que a organizacao atribui a quem participa da campanha, para o certificado. Zero significa certificado sem horas'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='meta_quantidade',
            field=models.PositiveIntegerField(blank=True, help_text='Quanto a campanha pretende arrecadar. Opcional: sem meta, a tela mostra apenas o total, sem barra de progresso', null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='modalidade',
            field=models.CharField(choices=[('presencial', 'Acao presencial'), ('doacao', 'Campanha de doacao')], db_index=True, default='presencial', help_text='Presencial mede tempo; doacao mede quantidade arrecadada', max_length=12),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='unidade_medida',
            field=models.CharField(blank=True, default='', help_text='Como a arrecadacao e contada, no plural: pecas de agasalho, quilos de alimento, litros de leite', max_length=60),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='vagas',
            field=models.PositiveIntegerField(default=1, help_text='Ignorado na campanha de doacao, que nao limita participantes'),
        ),
    ]
