# Generated by Django 5.2.14 on 2026-05-07 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAtivacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('tipo', models.CharField(choices=[('ativacao', 'Ativação'), ('reset_senha', 'Recuperação de Senha')], max_length=15)),
                ('tentativas', models.IntegerField(default=0)),
                ('data_expiracao', models.DateTimeField()),
                ('utilizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codigo_ativacao',
            },
        ),
    ]
