# Generated by Django 5.2.14 on 2026-05-07 23:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_codigoativacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleGlobal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('ong', 'Organização')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_globais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_global',
                'unique_together': {('usuario', 'role')},
            },
        ),
    ]
