# Generated by Django 5.2.14 on 2026-05-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_roleglobal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoativacao',
            name='codigo',
            field=models.CharField(help_text='Hash bcrypt do codigo de ativacao', max_length=128),
        ),
    ]
