# Generated by Django 5.2.14 on 2026-08-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_alter_codigoativacao_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Matrícula institucional, usada no pré-cadastro pela coordenação', max_length=20),
        ),
    ]
