# Generated by Django 5.2.14 on 2026-08-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_usuario_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('f', 'Feminino'), ('m', 'Masculino'), ('n', 'Prefiro não informar')], default='n', help_text='Usado apenas para flexionar o nome do perfil na interface', max_length=1),
        ),
    ]
