# Generated by Django 5.2.14 on 2026-08-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0006_usuario_genero'),
        ('forum', '0007_disciplina_ementa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curso_coordenado',
            field=models.ForeignKey(blank=True, help_text='Preenchido apenas para quem coordena um curso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordenadores', to='forum.curso'),
        ),
    ]
