# Generated by Django 5.2.14 on 2026-08-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0007_usuario_curso_coordenado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='assinatura',
            field=models.ImageField(blank=True, help_text='Imagem da assinatura do responsavel, usada no certificado', null=True, upload_to='assinaturas/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo_responsavel',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_responsavel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
