# Generated by Django 5.2.14 on 2026-05-09 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('nova_resposta', 'Nova resposta no seu topico'), ('voto_recebido', 'Novo voto no seu post'), ('melhor_resposta', 'Sua resposta foi marcada como melhor'), ('reacao_persiste', 'Reacao "duvida persiste" na sua resposta'), ('denuncia_resolvida', 'Sua denuncia foi resolvida'), ('post_removido', 'Seu post foi removido por moderacao'), ('papel_disciplina', 'Voce foi adicionado a uma disciplina')], db_index=True, max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('objeto_id', models.UUIDField(blank=True, null=True)),
                ('lida', models.BooleanField(db_index=True, default=False)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(blank=True, help_text='Usuario que originou o evento (pode ser nulo em eventos do sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacao',
                'verbose_name_plural': 'Notificacoes',
                'db_table': 'notificacao',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinatario', 'lida'], name='notificacao_destina_bcd56a_idx'), models.Index(fields=['destinatario', '-created_at'], name='notificacao_destina_b89b18_idx')],
            },
        ),
    ]
