# Generated by Django 5.2.14 on 2026-05-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('nova_resposta', 'Nova resposta no seu topico'), ('voto_recebido', 'Novo voto no seu post'), ('melhor_resposta', 'Sua resposta foi marcada como melhor'), ('reacao_persiste', 'Reacao "duvida persiste" na sua resposta'), ('denuncia_resolvida', 'Sua denuncia foi resolvida'), ('post_removido', 'Seu post foi removido por moderacao'), ('papel_disciplina', 'Voce foi adicionado a uma disciplina'), ('inscricao_aprovada', 'Sua inscricao em voluntariado foi aprovada'), ('inscricao_rejeitada', 'Sua inscricao em voluntariado foi rejeitada'), ('inscricao_removida', 'Voce foi removido de uma oportunidade'), ('voluntariado_concluido', 'Sua participacao foi concluida e o certificado emitido')], db_index=True, max_length=30),
        ),
    ]
