# Generated by Django 5.2.14 on 2026-08-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('nova_resposta', 'Nova resposta no seu topico'), ('voto_recebido', 'Novo voto no seu post'), ('melhor_resposta', 'Sua resposta foi marcada como melhor'), ('reacao_persiste', 'Reacao "duvida persiste" na sua resposta'), ('denuncia_resolvida', 'Sua denuncia foi resolvida'), ('post_removido', 'Seu post foi removido por moderacao'), ('post_restrito', 'Sua publicacao foi restrita pela disciplina'), ('post_liberado', 'A restricao da sua publicacao foi removida'), ('papel_disciplina', 'Voce foi adicionado a uma disciplina'), ('ajuda_solicitada', 'Pedido de ajuda em um grupo de trabalho'), ('ajuda_respondida', 'Seu pedido de ajuda foi respondido'), ('grupo_formado', 'Voce foi incluido em um grupo de trabalho'), ('mensagem_grupo', 'Nova mensagem no seu grupo'), ('inscricao_aprovada', 'Sua inscricao em voluntariado foi aprovada'), ('inscricao_rejeitada', 'Sua inscricao em voluntariado foi rejeitada'), ('inscricao_removida', 'Voce foi removido de uma oportunidade'), ('voluntariado_concluido', 'Sua participacao foi concluida e o certificado emitido')], db_index=True, max_length=30),
        ),
    ]
